### ISSUE TITLE
data sharing & versioning

### ISSUE THREAD

**Issue by badgley** [FoRTExperiment/rubisco-gpp#10]
Where do we want to put data we're generating? 

I personally dislike versioning data inside the repo, even with something like `git-lfs`. 

We could use the team drive from rubisco workshop or I could provision a new team drive as well. Other solutions folks like?

**Comment by badgley** [comment]
And this *just* became an issue.
Technically, we are not allowed to redistribute OneFlux data, meaning we cannot have a version of the data included in this repo.

**Comment by badgley** [comment]
I can create a google drive and share w ppl? 
welcome to the 21st century -- this still isn't a solved problem...

**Comment by ashiklom** [comment]
Private-ish shared Google Drive folder works for me!

**Comment by badgley** [comment]
great -- I made one that I'll sync the oneflux/cosore data to. folks can just email me for link!
