### ISSUE TITLE
Time scale for analysis

### ISSUE THREAD

**Issue by badgley** [FoRTExperiment/rubisco-gpp#12]
What is the time step we want to roll with for these analyses? The choices seem to be: daily vs ~hourly (sub-daily!). 

Looking through the MMS example from last October, looks like we took the CSR fluxes up to daily and then did our analysis on top of that. That will play well with the NIRv data, which we can spit out at daily scale really easily. 

In the world where we want daily, I need some direction from @bpbond and/or @ashiklom about how to appropriately combine these COSORE data. Specifically, how should I deal with aggregation along `CSR_PORT`?

In the world where we want sub-daily, we're going to need to do something like NIRv * PAR, which will can get pretty ugly, namely because the structure-function relationship can really explode on shorter intervals. 

Once we sort this out [and #10, re: not re-distributing OneFLUX data outside the AmeriFlux portal], we're basically there in terms of data munging.  

https://www.youtube.com/watch?v=Gmrh42foUsg
🚀

**Comment by badgley** [comment]
@bpbond pinging for guidance

**Comment by ashiklom** [comment]
My inclination is to use the highest (shortest) time resolution that the core datasets (COSORE and Fluxnet) have in common. So hourly or 30 minute. A big advantage of COSORE is the high temporal resolution of the data, and it seems like a waste to aggregate to daily.

That said, if we adopt a fully Bayesian paradigm, we could use multiple different datasets with different temporal resolutions. Namely, we can use daily GPP estimated from NIRv as an additional constraint by comparing against the average estimated GPP from flux tower NEE + COSORE. Back in grad school, we build a very simple Bayesian GPP forecast model ([repo](https://github.com/ashiklom/GPP), [model](https://github.com/ashiklom/GPP/blob/master/gpp.lue.simple.bug)) for a class project -- I wonder if we could do something similar here.

I can't speak to aggregation over `CSR_PORT` -- that's a @bpbond question.

**Comment by bpbond** [comment]
Sorry for the slow response @badgley - this coincided with a vacation for me. I had been thinking daily was our shortest, but @ashiklom makes a good point re trying to use the full time resolution. I definitely would say don't push and try to do something with NIRv that doesn't make sense here; not every data stream will apply or make sense at every timescale.

And, @badgley , glam rock, really?!? 🤦

**Comment by badgley** [comment]
@bpbond how should I handle data along a single `CSR_PORT` if I'm doing aggregation of any kind? 

My current thinking is I'll make a hourly, daily, and weekly aggregation and we can figure out what to do from those data later.

**Comment by bpbond** [comment]
That makes sense to me (?) I think. Wait, do you mean average across ports?

**Comment by badgley** [comment]
The COSORE data has a dimension of `CSR_PORT` -- I guess I was thinking that it might be possible that some records include multiple instruments hooked up the same same data logger and, therefore, getting a 'site level' average might require some sort of explicit treatment of individual ports. Or am I good to just grand average anything and everything contained within a cosore database file?

**Comment by bpbond** [comment]
I think you can just grand average. The only thing to be careful about is to make sure the port is measuring what you think it's measuring–see `CSR_MSMT_VAR`. You want Rs, presumably, not e.g. Rh or NEE.

**Comment by badgley** [comment]
@bpbond so I'm handling `CSR_PORT` and mapping to `CSR_MSMT_VAR` -- I also made the executive decision that `CSR_TREATMENT` has to be `None`, as opposed to things like `trenched` or `girdled` -- that seem reasonable to you? 

https://github.com/FoRTExperiment/rubisco-gpp/blob/1193a37d0750da462c1cb5561fae846bdfb77ff2/munge_data.py#L165

**Comment by bpbond** [comment]
Definitely.  👍
