### ISSUE TITLE
tz in COSORE 

### ISSUE THREAD

**Issue by badgley** [FoRTExperiment/rubisco-gpp#15]
@bpbond 

just double checking here -- the COSORE `description.csv` lists timezones like `ETC\GMT+5`. I'm interpreting this to mean that the underlying data does not respect day light savings time, but instead has a fixed offset from UTC of 5 hours.

**Comment by bpbond** [comment]
That's correct. Daylight savings is a blight on humanity and no science timestamps should ever include it.  😉

**Comment by badgley** [comment]
good to know you don't feel too strongly about DST!
