### ISSUE TITLE
write permission, please

### ISSUE THREAD

**Issue by badgley** [FoRTExperiment/rubisco-gpp#8]
![image](https://user-images.githubusercontent.com/1392400/87061754-29690080-c1da-11ea-9bac-eb10e1b27362.png)

Ah! Looks like I don't have write permissions. Do you want me to contribute pull requests from my fork? 
@bpbond

**Comment by bpbond** [comment]
Hang on, adding you

**Comment by badgley** [comment]
cooking with gas! 
https://www.youtube.com/watch?v=4Hihge6FFVw

**Comment by bpbond** [comment]
Hahahaha help me I just watched that whole video. 🎸

**Comment by badgley** [comment]
are you kidding me? the playlist is amazing. I strongly suggest all Flux Finality code be written while listening to Motley Crue.
